version: '3'

services:
  api_server:
    build:
      context: .
      dockerfile: Docker/Dockerfile.api
    ports:
      - "8000:8000" # Expose Gunicorn port

  nginx:
    build:
      context: .
      dockerfile: Docker/Dockerfile.nginx
    ports:
      - "80:80" # Expose Nginx port
    depends_on:
      - api_server
